# This is a basic workflow to help you get started with Actions
 
name:
  TomoScan healthcheck
 
  # Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow every 10 minutes
  schedule:
    - cron: "*/10 * * * *"
 
env:
  # Notification settings
  SLACK_HOOK_KEY: ${{ secrets.SLACK_HOOK_KEY }}
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_BOTNAME: ${{ secrets.SLACK_BOTNAME }}
  SLACK_BOT_ICON: ${{ secrets.SLACK_BOT_ICON }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT_ID }}
  PREFIX_MESSAGE: ${{ secrets.TOMOSCAN_PREFIX_MESSAGE }}


  # destination server information
  TOMOSCAN_ENDPOINT: ${{ secrets.TOMOSCAN_ENDPOINT }}


      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # setup
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Run script
      - name: Run healtchcheck script
        run: npm install && cd tomoscan && node index.js